stages:
  - test
  - build
  - deploy

realizar_testes:
  stage: test
  # mario 
  image:  node:22-alpine3.23   
  before_script:
    - cd app/
    - npm install
  script:
    - npm test
  artifacts:
    when: always
    reports:
        junit: app/junit.xml
  
build_images:
  stage: build
  needs:
    - realizar_testes
  # mario 29.1 e 29.1-dind
  image: docker:29.1
  services:
    - docker:29.1-dind
  
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  
  script:
    # mario: marioltf/gitlab-cicdv2-node:1.0
    - docker build -t marioltf/gitlab-cicdv2-node:1.0 .
    - docker push marioltf/gitlab-cicdv2-node:1.0

deploy_dev:
  stage: deploy
  needs:
    - build_images
  tags:
    - gcp
  script:
    # mario: marioltf/gitlab-cicdv2-node:1.0
    - docker run -d --name nodeapp -p 3000:3000 marioltf/gitlab-cicdv2-node:1.0